export const types = {
  SEARCH_USER: 'ADMIN/SEARCH_USER',
  CHANGE_USER_STATUS: 'ADMIN/CHANGE_USER_STATUS',
  DELETE_USER: 'ADMIN/DELETE_USER',
  SEARCH_PUBLICATION: 'ADMIN/SEARCH_PUBLICATION',
  CHANGE_PUBLICATION_APPROVAL: 'CHANGE_PUBLICATION_APPROVAL',
  DELETE_PUBLICATION: 'ADMIN/DELETE_PUBLICATION',
  SEARCH_REPORT: 'ADMIN/SEARCH_REPORT',
  CHANGE_REPORT_STATUS: 'ADMIN/CHANGE_REPORT_STATUS',
  DELETE_REPORT: 'ADMIN/DELETE_REPORT',
};
