export const CREATE_COMMENT = 'RENTAL_PLACE/CREATE_COMMENT';
export const UPDATE_COMMENT = 'RENTAL_PLACE/UPDATE_COMMENT';
export const DELETE_COMMENT = 'RENTAL_PLACE/DELETE_COMMENT';
export const RETRIEVE_COMMENT = 'RENTAL_PLACE/RETRIEVE_COMMENT';
export const RETRIEVE_ALL_COMMENTS = 'RENTAL_PLACE/RETRIEVE_ALL_COMMENTS';
