export const GET_COMMENT = 'STUDENT/GET_COMMENT';
export const CREATE_COMMENT = 'STUDENT/CREATE_COMMENT';
export const UPDATE_COMMENT = 'STUDENT/UPDATE_COMMENT';
export const DELETE_COMMENT = 'STUDENT/DELETE_COMMENT';
export const GET_ALL_COMMENTS = 'STUDENT/GET_ALL_COMMENTS';
