export const SEARCH_PUBLICATION = 'ADMIN/SEARCH_PUBLICATION';
export const DELETE_PUBLICATION = 'ADMIN/DELETE_PUBLICATION';
export const RETRIEVE_PUBLICATION = 'ADMIN/RETRIEVE_PUBLICATION';
export const RETRIEVE_ALL_PUBLICATIONS = 'ADMIN/RETRIEVE_ALL_PUBLICATIONS';
export const CHANGE_PUBLICATION_APPROVAL = 'ADMIN/CHANGE_PUBLICATION_APPROVAL';
