export const SEARCH_USER = 'ADMIN/SEARCH_USER';
export const DELETE_USER = 'ADMIN/DELETE_USER';
export const RETRIEVE_USER = 'ADMIN/RETRIEVE_USER';
export const RETRIEVE_ALL_USERS = 'ADMIN/RETRIEVE_ALL_USERS';
export const CHANGE_USER_STATUS = 'ADMIN/CHANGE_USER_STATUS';
