export const GET_USER = 'ADMIN/GET_USER';
export const SEARCH_USER = 'ADMIN/SEARCH_USER';
export const DELETE_USER = 'ADMIN/DELETE_USER';
export const GET_ALL_USERS = 'ADMIN/GET_ALL_USERS';
export const CHANGE_USER_STATUS = 'ADMIN/CHANGE_USER_STATUS';
