export const SEARCH_REPORT = 'ADMIN/SEARCH_REPORT';
export const DELETE_REPORT = 'ADMIN/DELETE_REPORT';
export const RETRIEVE_REPORT = 'ADMIN/RETRIEVE_REPORT';
export const RETRIEVE_ALL_REPORTS = 'ADMIN/RETRIEVE_ALL_REPORTS';
export const CHANGE_REPORT_STATUS = 'ADMIN/CHANGE_REPORT_STATUS';
