export const GET_PUBLICATION = 'ADMIN/GET_PUBLICATION';
export const SEARCH_PUBLICATION = 'ADMIN/SEARCH_PUBLICATION';
export const DELETE_PUBLICATION = 'ADMIN/DELETE_PUBLICATION';
export const GET_ALL_PUBLICATIONS = 'ADMIN/GET_ALL_PUBLICATIONS';
export const CHANGE_PUBLICATION_APPROVAL = 'ADMIN/CHANGE_PUBLICATION_APPROVAL';
