export const GET_REPORT = 'ADMIN/GET_REPORT';
export const SEARCH_REPORT = 'ADMIN/SEARCH_REPORT';
export const DELETE_REPORT = 'ADMIN/DELETE_REPORT';
export const GET_ALL_REPORTS = 'ADMIN/GET_ALL_REPORTS';
export const CHANGE_REPORT_STATUS = 'ADMIN/CHANGE_REPORT_STATUS';
