// =============================================================================

export const GET_PUBLICATION_PENDING = 'ADMIN/GET_PUBLICATION_PENDING';
export const GET_PUBLICATION_SUCCESS = 'ADMIN/GET_PUBLICATION_SUCCESS';
export const GET_PUBLICATION_ERROR = 'ADMIN/GET_PUBLICATION_ERROR';
export const GET_PUBLICATION = 'ADMIN/GET_PUBLICATION';

// =============================================================================

export const SEARCH_PUBLICATION_PENDING = 'ADMIN/SEARCH_PUBLICATION_PENDING';
export const SEARCH_PUBLICATION_SUCCESS = 'ADMIN/SEARCH_PUBLICATION_SUCCESS';
export const SEARCH_PUBLICATION_ERROR = 'ADMIN/SEARCH_PUBLICATION_ERROR';
export const SEARCH_PUBLICATION = 'ADMIN/SEARCH_PUBLICATION';

// =============================================================================

export const DELETE_PUBLICATION_PENDING = 'ADMIN/DELETE_PUBLICATION_PENDING';
export const DELETE_PUBLICATION_SUCCESS = 'ADMIN/DELETE_PUBLICATION_SUCCESS';
export const DELETE_PUBLICATION_ERROR = 'ADMIN/DELETE_PUBLICATION_ERROR';
export const DELETE_PUBLICATION = 'ADMIN/DELETE_PUBLICATION';

// =============================================================================

export const GET_ALL_PUBLICATIONS_PENDING =
  'ADMIN/GET_ALL_PUBLICATIONS_PENDING';
export const GET_ALL_PUBLICATIONS_SUCCESS =
  'ADMIN/GET_ALL_PUBLICATIONS_SUCCESS';
export const GET_ALL_PUBLICATIONS_ERROR = 'ADMIN/GET_ALL_PUBLICATIONS_ERROR';
export const GET_ALL_PUBLICATIONS = 'ADMIN/GET_ALL_PUBLICATIONS';

// =============================================================================

export const CHANGE_PUBLICATION_APPROVAL_PENDING =
  'ADMIN/CHANGE_PUBLICATION_APPROVAL_PENDING';
export const CHANGE_PUBLICATION_APPROVAL_SUCCESS =
  'ADMIN/CHANGE_PUBLICATION_APPROVAL_SUCCESS';
export const CHANGE_PUBLICATION_APPROVAL_ERROR =
  'ADMIN/CHANGE_PUBLICATION_APPROVAL_ERROR';
export const CHANGE_PUBLICATION_APPROVAL = 'ADMIN/CHANGE_PUBLICATION_APPROVAL';

// =============================================================================
