// =============================================================================

export const GET_PUBLICATION_PENDING = 'OWNER/GET_PUBLICATION_PENDING';
export const GET_PUBLICATION_SUCCESS = 'OWNER/GET_PUBLICATION_SUCCESS';
export const GET_PUBLICATION_ERROR = 'OWNER/GET_PUBLICATION_ERROR';
export const GET_PUBLICATION = 'OWNER/GET_PUBLICATION';

// =============================================================================

export const CREATE_PUBLICATION_PENDING = 'OWNER/CREATE_PUBLICATION_PENDING';
export const CREATE_PUBLICATION_SUCCESS = 'OWNER/CREATE_PUBLICATION_SUCCESS';
export const CREATE_PUBLICATION_ERROR = 'OWNER/CREATE_PUBLICATION_ERROR';
export const CREATE_PUBLICATION = 'OWNER/CREATE_PUBLICATION';

// =============================================================================

export const UPDATE_PUBLICATION_PENDING = 'OWNER/UPDATE_PUBLICATION_PENDING';
export const UPDATE_PUBLICATION_SUCCESS = 'OWNER/UPDATE_PUBLICATION_SUCCESS';
export const UPDATE_PUBLICATION_ERROR = 'OWNER/UPDATE_PUBLICATION_ERROR';
export const UPDATE_PUBLICATION = 'OWNER/UPDATE_PUBLICATION';

// =============================================================================

export const DELETE_PUBLICATION_PENDING = 'OWNER/DELETE_PUBLICATION_PENDING';
export const DELETE_PUBLICATION_SUCCESS = 'OWNER/DELETE_PUBLICATION_SUCCESS';
export const DELETE_PUBLICATION_ERROR = 'OWNER/DELETE_PUBLICATION_ERROR';
export const DELETE_PUBLICATION = 'OWNER/DELETE_PUBLICATION';

// =============================================================================

export const GET_ALL_PUBLICATIONS_PENDING =
  'OWNER/GET_ALL_PUBLICATIONS_PENDING';
export const GET_ALL_PUBLICATIONS_SUCCESS =
  'OWNER/GET_ALL_PUBLICATIONS_SUCCESS';
export const GET_ALL_PUBLICATIONS_ERROR = 'OWNER/GET_ALL_PUBLICATIONS_ERROR';
export const GET_ALL_PUBLICATIONS = 'OWNER/GET_ALL_PUBLICATIONS';

// =============================================================================

export const CHANGE_PUBLICATION_AVAILABILITY_PENDING =
  'OWNER/CHANGE_PUBLICATION_AVAILABILITY_PENDING';
export const CHANGE_PUBLICATION_AVAILABILITY_SUCCESS =
  'OWNER/CHANGE_PUBLICATION_AVAILABILITY_SUCCESS';
export const CHANGE_PUBLICATION_AVAILABILITY_ERROR =
  'OWNER/CHANGE_PUBLICATION_AVAILABILITY_ERROR';
export const CHANGE_PUBLICATION_AVAILABILITY =
  'OWNER/CHANGE_PUBLICATION_AVAILABILITY';

// =============================================================================
