export const GET_PUBLICATION = 'OWNER/GET_PUBLICATION';
export const CREATE_PUBLICATION = 'OWNER/CREATE_PUBLICATION';
export const UPDATE_PUBLICATION = 'OWNER/UPDATE_PUBLICATION';
export const DELETE_PUBLICATION = 'OWNER/DELETE_PUBLICATION';
export const GET_ALL_PUBLICATIONS = 'OWNER/GET_ALL_PUBLICATIONS';
export const CHANGE_PUBLICATION_AVAILABILITY =
  'OWNER/CHANGE_PUBLICATION_AVAILABILITY';
