export const CREATE_PUBLICATION = 'RENTAL_PLACE/CREATE_PUBLICATION';
export const UPDATE_PUBLICATION = 'RENTAL_PLACE/UPDATE_PUBLICATION';
export const DELETE_PUBLICATION = 'RENTAL_PLACE/DELETE_PUBLICATION';
export const RETRIEVE_PUBLICATION = 'RENTAL_PLACE/RETRIEVE_PUBLICATION';
export const RETRIEVE_ALL_PUBLICATION = 'RENTAL_PLACE/RETRIEVE_ALL_PUBLICATION';
export const CHANGE_PUBLICATION_AVAILABILITY =
  'RENTAL_PLACE/CHANGE_PUBLICATION_AVAILABILITY';
