export const GET_RENTAL_PLACES_PENDING =
  'rentalTypes/GET_RENTAL_PLACES_PENDING';
export const GET_RENTAL_PLACES_SUCCESS =
  'rentalTypes/GET_RENTAL_PLACES_SUCCESS';
export const GET_RENTAL_PLACES_ERROR = 'rentalTypes/GET_RENTAL_PLACES_ERROR';
