export const LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS';
export const LOGIN_PENDING = 'USER/LOGIN_PENDING';
export const LOGIN_FAILURE = 'USER/LOGIN_FAILURE';
export const LOGOUT = 'USER/LOGOUT';
export const FETCH_USER_SUCCESS = 'USER/FETCH_USER_SUCCESS';
export const FETCH_USER_PEDING = 'USER/FETCH_USER_PENDING';
export const FETCH_USER_FAILURE = 'USER/FETCH_USER_FAILURE';
