export enum Services {
  Baño = 'Baño',
  Cocina = 'Cocina',
  Lavadora = 'Lavadora',
  Elevador = 'Elevador',
  Amueblado = 'Amueblado',
  Estacionamiento = 'Estacionamiento',
  'Con balcón o patio' = 'Con balcón o patio',
  'Servicios públicos' = 'Servicios públicos',
  'Aire acondicionado' = 'Aire acondicionado',
  'Área de estudio' = 'Área de estudio',
  TV = 'TV',
  'Wi-Fi incluido' = 'Wi-Fi incluido',
  'Se admiten mascotas' = 'Se admiten mascotas',
}
