export const exampleFunction = (): void => console.log('Hello world');
export * from './types/Addres';
export * from './types/Auth.type';
export * from './types/Characteristic.type';
export * from './types/Image.type';
export * from './types/Message.type';
export * from './types/Owner.type';
export * from './types/Pagination.type';
export * from './types/Rate.type';
export * from './types/RentalPlace.type';
export * from './types/Report.type';
export * from './types/Rule.type';
export * from './types/School.type';
export * from './types/Security.type';
export * from './types/Service.type';
export * from './types/Student.type';
export * from './types/User.type';
export * from './utility/isServer';
