export const NameInput = {
  email: 'Correo electrónico',
  confirmPassword: 'Confirmar contraseña',
  currentPassword: 'Contraseña actual',
  newPassword: 'Contraseña nueva',
  newPasswordConfirmed: 'Confirmar nueva contraseña',
  firstName: 'Nombre',
  lastName: 'Apellido',
  description: 'Descripción',
  title: 'Título',
  reason: 'Motivo de la publicación',
  typeSpace: 'Tipo de espacio',
  gender: 'Género',
  price: 'Precio',
  availability: 'Disponibilidad',
  street: 'Calle y número',
  state: 'Estado',
  city: 'Municipio',
  neighborhood: 'Colonia',
  stateCode: 'Código Postal',
  reference: 'Referencias',
  zone: 'Descripción de la zona',
  rentalPlace: 'Descripción de la vivienda',
  services: 'Servicios',
  rules: 'Reglas',
  security: 'Seguridad',
  fullName: 'Nombre completo',
  phone: 'Número de teléfono',
  birthDate: 'Fecha de nacimiento',
  aboutMe: 'Acerca de mi',
  userStatus: 'Estatus del usuario',
  reportStatus: 'Estatus del reporte',
  reportType: 'Tipo de reporte',
  reportReason: 'Motivo del reporte',
  date: 'Fecha',
  fromReport: 'Realizado por',
  toReport: 'Reporta a',
  descripcionProblem: 'Descripción del problema',
  postDetails: 'Estatus de la publicación',
  ownerPost: 'Creado por',
  comment: 'Comentario',
  userRole: 'Seleccione el tipo de rol',
};
