export const NameInput = {
  email: 'Correo electrónico',
  password: 'Contraseña',
  confirmPassword: 'Confirmar contraseña',
  firstName: 'Nombre',
  lastName: 'Apellido',
  description: 'Descripción',
  title: 'Título',
  reason: 'Motivo de la publicación',
  typeSpace: 'Tipo de espacio',
  gender: 'Género',
  price: 'Precio',
  availability: 'Disponibilidad',
  street: 'Calle y número',
  state: 'Estado',
  city: 'Municipio',
  neighborhood: 'Colonia',
  stateCode: 'Código Postal',
  reference: 'Referencias',
  zone: 'Descripción de la zona',
  rentalPlace: 'Descripción de la vivienda',
  services: 'Servicios',
  rules: 'Reglas',
  security: 'Seguridad',
  fullName: 'Nombre completo',
  phone: 'Número de teléfono',
  birthday: 'Fecha de nacimiento',
  aboutMe: 'Acerca de mi',
  userStatus: 'Status del usuario',
};
