export const States = [
  { value: 'Aguascalientes', name: 'Aguascalientes' },
  { value: 'Baja California', name: 'Baja California' },
  { value: 'Baja California Sur', name: 'Baja California Sur' },
  { value: 'Chihuahua', name: 'Chihuahua' },
  { value: 'Chiapas', name: 'Chiapas' },
  { value: 'Campeche', name: 'Campeche' },
  { value: 'Ciudad De México', name: 'Ciudad De México' },
  { value: 'Coahuila', name: 'Coahuila' },
  { value: 'Colima', name: 'Colima' },
  { value: 'Durango', name: 'Durango' },
  { value: 'Guerrero', name: 'Guerrero' },
  { value: 'Guanajuato', name: 'Guanajuato' },
  { value: 'Hidalgo', name: 'Hidalgo' },
  { value: 'Jalisco', name: 'Jalisco' },
  { value: 'Michoacan', name: 'Michoacan' },
  { value: 'Estado De México', name: 'Estado De México' },
  { value: 'Morelos', name: 'Morelos' },
  { value: 'Nayarit', name: 'Nayarit' },
  { value: 'Nuevo León', name: 'Nuevo León' },
  { value: 'Oaxaca', name: 'Oaxaca' },
  { value: 'Puebla', name: 'Puebla' },
  { value: 'Quintana Roo', name: 'Quintana Roo' },
  { value: 'Queretaro', name: 'Queretaro' },
  { value: 'Sinaloa', name: 'Sinaloa' },
  { value: 'San Luis Potosí', name: 'San Luis Potosí' },
  { value: 'Sonora', name: 'Sonora' },
  { value: 'Tabasco', name: 'Tabasco' },
  { value: 'Tlaxcala', name: 'Tlaxcala' },
  { value: 'Tamaulipas', name: 'Tamaulipas' },
  { value: 'Veracruz', name: 'Veracruz' },
  { value: 'Yucatan', name: 'Yucatan' },
  { value: 'Zacatecas', name: 'Zacatecas' },
];
